[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "preserve"
override_spacing = false

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x0"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_sequence = true

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"
localhost = "http://localhost:8545"
anvil = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
polygon = { key = "${ETHERSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
localhost = { key = "none", url = "http://localhost:8545/api" }
anvil = { key = "none", url = "http://localhost:8545/api" }
"anvil-hardhat" = { key = "none", url = "http://localhost:8545/api" }
