[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "021945a4868c8373d4ce5a7b93eac98da17ec1cc", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "021945a4868c8373d4ce5a7b93eac98da17ec1cc",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


