[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "049be3b3636b657b52a9082e6ca7bbd3fb63580f", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "049be3b3636b657b52a9082e6ca7bbd3fb63580f",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


