[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "32425ac8ab6856442b306ef7f4a9ad38721b2c47", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "32425ac8ab6856442b306ef7f4a9ad38721b2c47",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


