[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "744a6b6471c802ef18f0088e14f2f954db7e1487", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "744a6b6471c802ef18f0088e14f2f954db7e1487",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


