[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "7e3abb9552f7f9e5ac2e053df0bf1a9df507a81e", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "7e3abb9552f7f9e5ac2e053df0bf1a9df507a81e",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


