[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "5b54bdb3f096a948fd02fa0fb8fec8fb9aacb03a", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "5b54bdb3f096a948fd02fa0fb8fec8fb9aacb03a",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


