[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "0d0613b14af47d1ecfe0e78d3e028854a87ad62d", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "0d0613b14af47d1ecfe0e78d3e028854a87ad62d",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


