[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "06ff7f54fc9b8728535f6ac5120e27dee1b58d5b", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "06ff7f54fc9b8728535f6ac5120e27dee1b58d5b",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


